### ISSUE TITLE
Playback from memory given input pointer and size

### ISSUE THREAD

**Issue by rmoog** [katajakasa/SDL_kitchensink#22]
I've got a use case for this player in an opensource game engine, but it's required that the media player be able to play from char *, given the size of the cached media file. I've forked and done a commit of my work so far, but it segfaults. Could you please take a look?
https://github.com/rmoog/SDL_kitchensink/commit/04c315e88692573418fc84fc37804df2379f8410

**Comment by katajakasa** [comment]
Not quite sure what you're trying to do. Check out the official example: http://www.ffmpeg.org/doxygen/trunk/doc_2examples_2avio_reading_8c-example.html

**Comment by katajakasa** [comment]
This is now implemented in 96fbbaae3957943693de48b3538e7f394ffb9e07 via ffmpeg AVIO.
