### ISSUE TITLE
Please add a version to the SONAME

### ISSUE THREAD

**Issue by OdyX** [katajakasa/SDL_kitchensink#25]
SDL_kitchensink builds `/usr/lib/libSDL_kitchensink.so` which gets installed in a public library directory, but has an SONAME that does not contain any versioning information, either after the .so or before it and set off by a hyphen. It cannot therefore be represented in the shlibs system, and if linked by binaries its interface cannot safely change. There is no backward-compatible way to migrate programs linked against it to a new ABI.

(See https://lintian.debian.org/tags/shlib-without-versioned-soname.html for more documentation )

**Comment by katajakasa** [comment]
VERSION and SOVERSION for cmake added in 09cf13b9256c8bc599188cb2f2c6f8322d632abb. Please test, I don't currently have access to linux machine :)

**Comment by OdyX** [comment]
That works; thank yo very much!
