### ISSUE TITLE
Issue looping video

### ISSUE THREAD

**Issue by ChillyWillyGuru** [katajakasa/SDL_kitchensink#32]
While trying to make videos loop, I ran into something. Basically, the video simply quits decoding. The way I do looping is when the video stops without an error, I assume it's at the end, so I seek to 0 and start it playing again.

    Kit_PlayerSeek(cin->player, 0.0);
    Kit_PlayerPlay(cin->player);

In looking at the code, it looks like a mutex is left locked. In the thread main loop, there's this:

            if(SDL_LockMutex(player->dec_lock) == 0) {
                while((ret = _DemuxStream(player)) == -1);
                if(ret == 1) {
                    player->state = KIT_STOPPED;
                    continue;
                }

There's no corresponding unlock before the continue.

Also, all my videos end about 7 to 8 seconds early, no matter the length. Not sure what the deal with that is. :)

**Comment by katajakasa** [comment]
Hey, good catch, will fix.

Also, the videos end early because decoder is done and closes the player when there is still things to show in buffers. That's also on my TODO list (along with pile of other bugs :) )

**Comment by ChillyWillyGuru** [comment]
That was my guess on the matter, but it's good to have confirmation. And if I spot anything else, I'll let you know. I really love this library - makes it pretty easy to build a movie viewer into a game.

**Comment by ChillyWillyGuru** [comment]
That was my guess on the matter, but it's good to have confirmation. And if I spot anything else, I'll let you know. I really love this library - makes it pretty easy to build a movie viewer into a game.

As to the looping, I can confirm that sticking an unlock in there fixes the issue. I did this to the code and recompiled...

            // Get more data from demuxer, decode. Wait a bit if there's no more work for now.
            if(SDL_LockMutex(player->dec_lock) == 0) {
                while((ret = _DemuxStream(player)) == -1);
                if(ret == 1) {
                    player->state = KIT_STOPPED;
                    // Free decoder thread lock.
                    SDL_UnlockMutex(player->dec_lock);
                    continue;
                }

and it loops now. However, I'd think the decoded but not played buffers then comes into play - I don't see the first 8 seconds of the video on loops. Maybe it's not quite seeking to the right place because of all the unused buffers... or however buffers are tracked internally have to expend those 8 extra seconds of data before filling new buffers.

**Comment by ChillyWillyGuru** [comment]
Okay, I found a way to make it play the whole thing. In _DemuxStream, I changed the part of the code that reads the next av packet like this:

    // Attempt to read frame. Just return here if it fails.
    AVPacket *packet = av_packet_alloc();
    if(av_read_frame(format_ctx, packet) < 0) {
        av_packet_free(&packet);
        for(int i = 0; i < 3; i++) {
            if(decoders[i] == NULL)
                continue;
            // Check if decoder still has buffers
            if(Kit_PeekDecoderOutput(decoders[i]))
                return 0;
        }
        return 1;
    }

Now if any decoder still has a buffer, it returns okay. However, I STILL don't get the first 7/8 seconds of the video on a loop. I do get this message from ffmpeg:

[h264 @ 0x55d4355ec9e0] co located POCs unavailable
[h264 @ 0x55d4355ec9e0] co located POCs unavailable

**Comment by ChillyWillyGuru** [comment]
Working fine. I think you can close this one. :)
