### ISSUE TITLE
Add support of Android assets directory

### ISSUE THREAD

**Issue by Skywalker13** [katajakasa/SDL_kitchensink#41]
Like `SDL_RWFromFile`, it should be possible to open a video/audio file from the Android assets directory.

**Comment by katajakasa** [comment]
Hey!

This is something that I already happened to have under construction. Now committed & pushed @ https://github.com/katajakasa/SDL_kitchensink/pull/42

If you have the time, please test :)

**Comment by Skywalker13** [comment]
Oh great, I will test ASAP :-)

**Comment by katajakasa** [comment]
Had some time and tested this locally -- seemed to work okay. Tagged to release 1.0.3.

I'll close this ticket as done -- if there are problems, please open up a new ticket :)

**Comment by Skywalker13** [comment]
OK, sorry.. I'm too busy..
