### ISSUE TITLE
Typo (av pixel format)

### ISSUE THREAD

**Issue by ebachard** [katajakasa/SDL_kitchensink#44]
Hi,

In src/internal/video/kitvideo.c, we have:

````
    17	enum AVPixelFormat supported_list[] = {
    18	    AV_PIX_FMT_YUV420P,
    19	    AV_PIX_FMT_YUYV422,
    20	    AV_PIX_FMT_UYVY422,
    21	    AV_PIX_FMT_NV12,
    22	    AV_PIX_FMT_NV12,
    23	    AV_PIX_FMT_RGB24,
    24	    AV_PIX_FMT_BGR24,
    25	    AV_PIX_FMT_RGB555,

````
Looks like the AV_PIX_FMT_NV12 is declared twice.

Suggested change: https://github.com/ebachard/SDL_kitchensink/commit/66c320153ce3ec0b6f102efce2e3972332883bcb

**Comment by katajakasa** [comment]
Right. It should be AV_PIX_FMT_NV21. Thanks for the issue, I'll roll a fix when I have a little bit of time.
