### ISSUE TITLE
mutex lock/unlock problem when time left ~< 10 sec

### ISSUE THREAD

**Issue by Cpasjuste** [katajakasa/SDL_kitchensink#50]
Hi,

I started playing with your library today to see if it could help in fast prototyping, it does. That's said, i spotted a bug where you won't be able to seek backward or even stop the player when you are in the last seconds of a video stream (say around 10 second before the end of the stream). 
I didn't find the time yet to go deeply into your sources, but i think the "dec_lock" is never unlocked, and so the program hang.

**Comment by katajakasa** [comment]
Yup, this is a bug. Also occurs in some videos if you seek right after a previous seek fast enough. This is likely due to my crap code in decoder thread -- that part needs some rethinking.

**Comment by katajakasa** [comment]
Fixed in master. Hopyfully. 

Better decoder coming .... someday >_<
