### ISSUE TITLE
CMake assumes we want an NMake Makefile if we're on Windows

### ISSUE THREAD

**Issue by rmoog** [katajakasa/SDL_kitchensink#51]
This assumption is just wrong. There are Unix development environments for Windows like Cygwin and msys2, and there are ways to detect if we are running in them. Cygwin and msys2 should for example be able to call `uname -a` on Windows and return something like `MINGW64_NT-10.0 hostname 2.11.1(0.329/5/3) 2018-09-10 14:19 x86_64 Msys`, while NMake would have no clue what did we just ask for.

**Comment by katajakasa** [comment]
NMake is a default assumption that cmake seems to make. You can override it by telling cmake to use something else, eg. '-G "MSYS Makefiles"'.

**Comment by katajakasa** [comment]
Closing as this is a cmake issue, not SDL_kitchensink one.
