### ISSUE TITLE
SDL.h can't be found on msys2

### ISSUE THREAD

**Issue by rmoog** [katajakasa/SDL_kitchensink#52]
msys2 holds includes and libs in respective toolchain directories, and it has start scripts that let you fire up the console fully configured for the desired compile target (amd64 or x86). In the case of amd64, SDL.h lives in `/mingw64/include/SDL2/SDL.h` and the include dir in amd64 msys2 gcc is `/mingw64/include`.

`kitaudio.c` searches for SDL.h in the configured usr catalog, so to support that, maybe we could use something that asks `sdl2-config` for locations, or, add preprocessor defines that try to guess if we're on msys2 and then ask for SDL.h from `<SDL2/SDL.h>`? Both solutions would work fine:
```
$ sdl2-config --cflags
-I/mingw64/include/SDL2 -Dmain=SDL_main
```

**Comment by katajakasa** [comment]
I could probably live with sdl2-config. Also updating cmake and using cmakes own sdl2 finder might work. I will take a look at this sooner or later, but would also greatly appreciate a PR :)

**Comment by katajakasa** [comment]
Tried with MSYS2 and could not replicate. In addition, if this happens to be an issue, the ticket should be raised on cmake side since we use cmake SDL2 finder :/
