### ISSUE TITLE
Can not make on ubuntu 18.04

### ISSUE THREAD

**Issue by flykule** [katajakasa/SDL_kitchensink#55]
Hello, I can not run `make -j` command on my computer. Here is the log:

[ 90%] Building C object CMakeFiles/SDL_kitchensink.dir/src/internal/utils/kitringbuffer.c.o
[ 92%] Building C object CMakeFiles/SDL_kitchensink_static.dir/src/internal/subtitle/renderers/kitsubrenderer.c.o
[ 95%] Building C object CMakeFiles/SDL_kitchensink.dir/src/internal/subtitle/renderers/kitsubass.c.o
[ 97%] Linking C shared library libSDL_kitchensink.so
[100%] Linking C static library libSDL_kitchensink_static.a
[100%] Built target SDL_kitchensink_static
/usr/bin/ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/SDL_kitchensink.dir/build.make:568: recipe for target 'libSDL_kitchensink.so.1.0.7' failed
make[2]: *** [libSDL_kitchensink.so.1.0.7] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/SDL_kitchensink.dir/all' failed
make[1]: *** [CMakeFiles/SDL_kitchensink.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Whate shall I do to make it work?

**Comment by katajakasa** [comment]
Okay, tested with ubuntu 18.10 on virtualbox, and did not encounter this.

Are you using x86_64 ubuntu ? What gcc and ffmpeg version ?

**Comment by katajakasa** [comment]
@flykule Ok, good to know it works.

I think I'll leave that out from the readme, though. Since this is ffmpeg compilation issue, it should be in their readme. If we start listing all possible issues in this project, the list will soon be a kilometer long ;)
